//! Shared JXL/image preprocessing utilities
//!
//! Common functions used by both `img_av1` and `img_hevc` lossless converters:
//! - JXL file health verification
//! - Image format preprocessing for cjxl compatibility
//! - Fallback encoding pipelines (`ImageMagick`, `FFmpeg`)
//! - ICC Profile extraction and preservation

use std::path::Path;

/// Extract ICC Profile from source image and return temp file path
#[must_use]
pub fn extract_icc_profile(src: &Path) -> Option<tempfile::NamedTempFile> {
    if !crate::image_builders::ExiftoolBuilder::check_available() {
        return None;
    }

    let temp_icc = tempfile::Builder::new().suffix(".icc").tempfile().ok()?;
    let output = crate::image_builders::ExiftoolBuilder::new()
        .input(src)
        .extract_icc_profile()
        .build()
        .output()
        .ok()?;

    if output.status.success() && !output.stdout.is_empty() {
        std::fs::write(temp_icc.path(), &output.stdout).ok()?;
        Some(temp_icc)
    } else {
        None
    }
}

/// Returns true if a cjxl stderr output indicates an ICC D50 illuminant rounding error.
///
/// This is a known issue with ICC profiles generated by Capture One and some professional
/// cameras where the D50 tag has a 2-byte rounding deviation from the ICC spec.
#[must_use]
pub fn is_icc_rounding_error(stderr: &str) -> bool {
    stderr.contains("Invalid ICC profile")
        || stderr.contains("bad connection space")
        || stderr.contains("ICC_Profile")
            && (stderr.contains("invalid") || stderr.contains("rejected"))
}

/// Extract ICC Profile and apply D50 illuminant rounding patch before returning.
///
/// Only call this after `is_icc_rounding_error` returns true on a failed cjxl run.
/// Patches bytes [68..80] to the canonical D50 values per ICC spec.
#[must_use]
pub fn extract_icc_with_d50_patch(src: &Path) -> Option<tempfile::NamedTempFile> {
    if !crate::image_builders::ExiftoolBuilder::check_available() {
        return None;
    }

    let temp_icc = tempfile::Builder::new().suffix(".icc").tempfile().ok()?;
    let output = crate::image_builders::ExiftoolBuilder::new()
        .input(src)
        .extract_icc_profile()
        .build()
        .output()
        .ok()?;

    if output.status.success() && !output.stdout.is_empty() {
        let mut icc_data = output.stdout;
        if icc_data.len() >= 80 {
            // Apply D50 illuminant rounding patch (Capture One / some cameras emit 0x...D32B
            // instead of the ICC-spec 0x...D32D, causing cjxl <= v0.10 to reject the profile)
            let d50_standard = [
                0x00, 0x00, 0xf6, 0xd6, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0xd3, 0x2d,
            ];
            if let Some(slice) = icc_data.get_mut(68..80) {
                slice.copy_from_slice(&d50_standard);
            }
        }
        std::fs::write(temp_icc.path(), &icc_data).ok()?;
        Some(temp_icc)
    } else {
        None
    }
}

/// Verify that a JXL file is valid by checking its signature and optionally running jxlinfo.
/// Verify the health of a JXL file.
///
/// # Errors
/// Returns an error message if the file is corrupt.
pub fn verify_jxl_health(path: &Path) -> Result<(), String> {
    use std::io::Read;
    let mut file = std::fs::File::open(path).map_err(|e| e.to_string())?;
    let mut sig = [0u8; 2];
    file.read_exact(&mut sig).map_err(|e| e.to_string())?;

    if sig != [0xFF, 0x0A] && sig != [0x00, 0x00] {
        return Err("Invalid JXL file signature".to_string());
    }

    if crate::tool_builders::JxlinfoBuilder::check_available() {
        let result = crate::tool_builders::JxlinfoBuilder::new()
            .input(path)
            .build()
            .output();

        if let Ok(output) = result {
            if !output.status.success() {
                let stderr = String::from_utf8_lossy(&output.stderr);
                return Err(format!(
                    "JXL health check failed (jxlinfo): {}",
                    stderr.trim()
                ));
            }
        }
    }

    Ok(())
}

/// Check whether a JXL file already contains an embedded ICC profile.
///
/// Uses `exiftool -icc_profile -b` — returns `true` if the profile blob is non-empty.
/// Falls back to `false` on any error (tool missing, I/O failure) so the caller can safely
/// decide whether to inject ICC via `ExifTool` as a fallback.
#[must_use]
pub fn verify_jxl_has_icc(path: &Path) -> bool {
    if !crate::image_builders::ExiftoolBuilder::check_available() {
        return false; // Cannot verify; assume absent to trigger fallback
    }
    let result = crate::image_builders::ExiftoolBuilder::new()
        .input(path)
        .extract_icc_profile()
        .build()
        .output();
    match result {
        Ok(out) => out.status.success() && !out.stdout.is_empty(),
        Err(_) => false,
    }
}

/// True when cjxl failed due to grayscale PNG + ICC profile (libpng: "RGB color space not permitted on grayscale").
///
/// Only then do we retry with -strip to avoid metadata loss in the general case.
/// Enhanced to catch more variants of the error message.
#[must_use]
pub fn is_grayscale_icc_cjxl_error(stderr: &str) -> bool {
    let s = stderr.to_lowercase();
    // Match the specific pattern: ICC profile color space mismatch on grayscale PNG
    // Example: "libpng warning: iCCP: profile 'icc': 'RGB ': RGB color space not permitted on grayscale PNG"
    // Relaxed matching: check for libpng warning + grayscale + icc/color space issues
    let has_grayscale_issue = s.contains("grayscale") || s.contains("pixel data");
    let has_icc_issue = s.contains("iccp")
        || s.contains("color space")
        || s.contains("icc profile")
        || s.contains("icc");
    let has_libpng_warning = s.contains("libpng warning") || s.contains("png warning");

    s.contains("rgb color space not permitted on grayscale")
        || (has_libpng_warning && has_grayscale_issue && has_icc_issue)
        || (s.contains("iccp") && s.contains("grayscale"))
        || (s.contains("pixel data") && s.contains("color space"))
}

/// True when cjxl failed with decode/pixel errors that may be helped by a simpler pipeline.
fn is_decode_or_pixel_cjxl_error(stderr: &str) -> bool {
    let s = stderr.to_lowercase();
    s.contains("getting pixel data failed")
        || s.contains("failed to decode")
        || s.contains("decoding failed")
        || s.contains("decode failed")
}

/// True when cjxl was killed by signal (OOM/crash) — stderr has version/encoding lines but no error.
/// In this case retrying at lower effort may succeed.
fn is_cjxl_signal_killed(stderr: &str) -> bool {
    let has_started = stderr.contains("JPEG XL encoder") || stderr.contains("Encoding [");
    let has_error = stderr.to_lowercase().contains("error")
        || stderr.contains("failed")
        || stderr.contains("Error");
    has_started && !has_error
}

/// Read the bit depth from a PNG file's IHDR chunk (byte offset 24).
/// Returns None if the file is not a valid PNG or cannot be read.
#[must_use]
pub fn get_png_bit_depth(path: &Path) -> Option<u8> {
    use std::io::Read;
    let mut f = std::fs::File::open(path).ok()?;
    let mut buf = [0u8; 25];
    f.read_exact(&mut buf).ok()?;
    // PNG signature is 8 bytes; IHDR: 4 len + 4 type + 13 data bytes.
    // Bit depth is the first byte of IHDR data, at offset 8+4+4+8 = 24.
    if &buf[0..8] != b"\x89PNG\r\n\x1a\n" {
        return None;
    }
    Some(buf[24])
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum JxlMetadataPolicy {
    Preserve,
    Strip,
}

impl JxlMetadataPolicy {
    const fn should_strip(self) -> bool {
        matches!(self, Self::Strip)
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum JxlIccPolicy {
    Preserve,
    NormalizeToSrgb,
}

impl JxlIccPolicy {
    const fn should_normalize(self) -> bool {
        matches!(self, Self::NormalizeToSrgb)
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum JxlMode {
    Normal,
    Ultimate,
}

impl JxlMode {
    const fn is_ultimate(self) -> bool {
        matches!(self, Self::Ultimate)
    }
}

#[derive(Debug, Clone, Copy)]
pub struct ImagemagickCjxlPipelineRequest<'a> {
    pub input: &'a Path,
    pub output: &'a Path,
    pub distance: f32,
    pub effort: u8,
    pub max_threads: usize,
    pub metadata_policy: JxlMetadataPolicy,
    pub output_depth: u8,
    pub icc_policy: JxlIccPolicy,
    pub apple_compat: bool,
}

#[derive(Debug, Clone, Copy)]
pub struct ModeLockedImagemagickCjxlPipelineRequest<'a> {
    pub input: &'a Path,
    pub output: &'a Path,
    pub distance: f32,
    pub max_threads: usize,
    pub metadata_policy: JxlMetadataPolicy,
    pub output_depth: u8,
    pub icc_policy: JxlIccPolicy,
    pub apple_compat: bool,
    pub mode: JxlMode,
}

/// Run the `cjxl` pipeline via `ImageMagick`.
/// - `metadata_policy`: preserve metadata or apply `-strip`
/// - `output_depth`: PNG bit depth to emit (8 or 16); use 8 only for confirmed 8-bit sources
/// - `icc_policy`: replaces embedded ICC with standard sRGB without truncating bit depth
/// - `apple_compat`: adds `--compress_boxes=0` to cjxl for Apple device compatibility
///
/// # Errors
/// Returns an error if the pipeline fails.
fn run_imagemagick_cjxl_pipeline_with_effort(
    request: ImagemagickCjxlPipelineRequest<'_>,
) -> std::result::Result<(), (bool, bool, String)> {
    use std::process::Stdio;
    let ImagemagickCjxlPipelineRequest {
        input,
        output,
        distance,
        effort,
        max_threads,
        metadata_policy,
        output_depth,
        icc_policy,
        apple_compat,
    } = request;
    debug_assert!(crate::constants::is_supported_jxl_effort(effort));

    let mut magick_builder = crate::image_builders::MagickBuilder::new();
    magick_builder
        .input(input)
        .strip(metadata_policy.should_strip())
        .use_stdout(true);

    magick_builder.depth(output_depth);

    if icc_policy.should_normalize() {
        magick_builder
            .define("png:preserve-colormap", "false")
            .set("colorspace", "sRGB");
    }

    let mut magick_proc = magick_builder.build().spawn().map_err(|e| {
        let line = format!("   ❌ ImageMagick not available or failed to start: {e}");
        crate::progress_mode::emit_stderr(&line);
        (false, false, String::new())
    })?;

    let magick_stdout = magick_proc.stdout.take().ok_or_else(|| {
        if let Err(err) = magick_proc.kill() {
            crate::progress_mode::emit_stderr(&format!(
                "   ⚠️ Failed to stop ImageMagick after stdout capture failure: {err}"
            ));
        }
        (false, false, String::new())
    })?;

    // Drain ImageMagick stderr in background to avoid blocking when pipe buffer fills.
    // Limit to 1MB to prevent memory issues in low-memory scenarios.
    let magick_stderr_thread = magick_proc.stderr.take().map(|stderr| {
        std::thread::spawn(move || {
            use std::io::Read;
            let mut s = String::new();
            if let Err(err) = stderr.take(1024 * 1024).read_to_string(&mut s) {
                crate::log_rare_error!("Stderr Pipe", "Failed to read ImageMagick stderr: {err}");
            }
            s
        })
    });

    let mut cjxl_builder = crate::jxl_builder::CjxlBuilder::new();
    cjxl_builder
        .use_stdin(true)
        .output(output)
        .distance(distance)
        .effort(effort)
        .threads(max_threads)
        .apple_compat(apple_compat);

    let mut cjxl_proc = cjxl_builder
        .build()
        .stdin(magick_stdout)
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|e| {
            let line = format!("   ❌ Failed to start cjxl process: {e}");
            crate::progress_mode::emit_stderr(&line);
            if let Err(err) = magick_proc.kill() {
                crate::progress_mode::emit_stderr(&format!(
                    "   ⚠️ Failed to stop ImageMagick after cjxl startup failure: {err}"
                ));
            }
            (false, false, String::new())
        })?;

    // Drain cjxl stderr in background so cjxl does not block when pipe buffer fills.
    // Limit to 1MB to prevent memory issues in low-memory scenarios.
    let cjxl_stderr_thread = cjxl_proc.stderr.take().map(|stderr| {
        std::thread::spawn(move || {
            use std::io::Read;
            let mut s = String::new();
            if let Err(err) = stderr.take(1024 * 1024).read_to_string(&mut s) {
                crate::log_rare_error!("Stderr Pipe", "Failed to read cjxl stderr: {err}");
            }
            s.trim().to_string()
        })
    });

    let magick_status = magick_proc.wait();
    let cjxl_status = cjxl_proc.wait();

    let magick_stderr = match magick_stderr_thread {
        Some(handle) => {
            if let Ok(stderr) = handle.join() {
                stderr
            } else {
                crate::log_rare_error!(
                    "Background Thread",
                    "ImageMagick stderr capture thread panicked"
                );
                String::new()
            }
        }
        None => String::new(),
    };
    let cjxl_stderr = match cjxl_stderr_thread {
        Some(handle) => {
            if let Ok(stderr) = handle.join() {
                stderr
            } else {
                crate::log_rare_error!("Background Thread", "cjxl stderr capture thread panicked");
                String::new()
            }
        }
        None => String::new(),
    };

    let magick_ok = match magick_status {
        Ok(status) if status.success() => true,
        Ok(status) => {
            let line = format!(
                "   ❌ ImageMagick failed with exit code: {:?}",
                status.code()
            );
            crate::progress_mode::emit_stderr(&line);
            if !magick_stderr.is_empty() {
                let line2 = format!(
                    "   📋 ImageMagick stderr: {}",
                    magick_stderr.lines().next().unwrap_or("")
                );
                crate::progress_mode::emit_stderr(&line2);
            }
            false
        }
        Err(e) => {
            let line = format!("   ❌ Failed to wait for ImageMagick: {e}");
            crate::progress_mode::emit_stderr(&line);
            false
        }
    };

    let cjxl_ok = match cjxl_status {
        Ok(status) if status.success() => true,
        Ok(status) => {
            let exit_code = status.code();
            // exit_code is None when process was terminated by signal (SIGKILL, SIGSEGV, etc.)
            if exit_code.is_none() {
                crate::log_pipeline_broken!(
                    "cjxl",
                    "Process terminated by signal (possible crash or OOM kill)"
                );
                if !cjxl_stderr.is_empty() {
                    crate::progress_mode::emit_stderr(&format!(
                        "   📋 cjxl stderr before termination: {cjxl_stderr}"
                    ));
                }
            } else {
                crate::log_upstream_error!("cjxl", "Failed with exit code: {:?}", exit_code);
                if !cjxl_stderr.is_empty() {
                    crate::progress_mode::emit_stderr(&format!("   📋 cjxl stderr: {cjxl_stderr}"));
                } else if let Some(code) = exit_code {
                    // [HARDENING] Try to provide more context if stderr is empty
                    if code == 1 {
                        crate::progress_mode::emit_stderr(
                            "   💡 Tip: Exit code 1 often indicates ICC mismatch or malformed metadata.",
                        );
                    }
                }
            }
            false
        }
        Err(e) => {
            crate::log_pipeline_broken!("cjxl", "Failed to wait for process: {}", e);
            false
        }
    };

    if magick_ok && cjxl_ok {
        Ok(())
    } else {
        Err((magick_ok, cjxl_ok, cjxl_stderr))
    }
}

/// Run the `ImageMagick` -> `cjxl` pipeline using the mode-locked JXL policy.
///
/// # Errors
/// Returns an error if the pipeline fails.
pub fn run_imagemagick_cjxl_pipeline(
    request: ModeLockedImagemagickCjxlPipelineRequest<'_>,
) -> std::result::Result<(), (bool, bool, String)> {
    run_imagemagick_cjxl_pipeline_with_effort(ImagemagickCjxlPipelineRequest {
        input: request.input,
        output: request.output,
        distance: crate::constants::jxl_distance_for_mode(
            request.distance,
            request.mode.is_ultimate(),
        ),
        effort: crate::constants::jxl_effort_for_mode(request.mode.is_ultimate()),
        max_threads: request.max_threads,
        metadata_policy: request.metadata_policy,
        output_depth: request.output_depth,
        icc_policy: request.icc_policy,
        apple_compat: request.apple_compat,
    })
}

/// `ImageMagick` → cjxl fallback pipeline for when direct cjxl encoding fails.
///
/// Fallback priority:
///
/// - No -strip, depth 16 (preserve metadata)
/// - grayscale+ICC error → -strip, depth 16
///   - still fails + decode/pixel error + 8-bit source → -strip, depth 8 (no quality loss)
///   - still fails + 16-bit source → normalize ICC to sRGB, keep depth 16
///     - still fails → error, refuse to downgrade
/// - decode/pixel error + 8-bit source → -strip, depth 8 (no quality loss)
/// - decode/pixel error + 16-bit source → normalize ICC to sRGB, keep depth 16
///   - still fails → error, refuse to silently downgrade
///
/// Fallback to `ImageMagick` for conversion if native tools fail.
///
/// # Errors
/// Returns an I/O error if conversion fails.
pub fn try_imagemagick_fallback_with_effort(
    input: &Path,
    output: &Path,
    distance: f32,
    effort: u8,
    max_threads: usize,
    apple_compat: bool,
) -> std::result::Result<(), std::io::Error> {
    use console::style;
    debug_assert!(crate::constants::is_supported_jxl_effort(effort));
    let base_request = ImagemagickCjxlPipelineRequest {
        input,
        output,
        distance,
        effort,
        max_threads,
        metadata_policy: JxlMetadataPolicy::Preserve,
        output_depth: 16,
        icc_policy: JxlIccPolicy::Preserve,
        apple_compat,
    };

    // Attempt 1: no -strip, depth 16, preserve metadata
    crate::progress_mode::emit_stderr(&format!(
        "   🔄 Attempt 1: Default (16-bit, preserve metadata) - {}",
        input.display()
    ));
    match run_imagemagick_cjxl_pipeline_with_effort(base_request) {
        Ok(()) => {
            crate::progress_mode::emit_stderr(&format!(
                "   {} Attempt 1 succeeded",
                style("✅").green()
            ));
            crate::progress_mode::fallback_success();
            return Ok(());
        }
        Err((magick_ok, cjxl_ok, stderr)) => {
            crate::progress_mode::emit_stderr(&format!(
                "   {} Attempt 1 failed (magick: {}, cjxl: {})",
                style("❌").red(),
                if magick_ok {
                    style("✓").green()
                } else {
                    style("✗").red()
                },
                if cjxl_ok {
                    style("✓").green()
                } else {
                    style("✗").red()
                }
            ));

            if magick_ok && !cjxl_ok && is_grayscale_icc_cjxl_error(&stderr) {
                // Attempt 2: -strip, depth 16 (drop bad ICC, keep bit depth)
                crate::progress_mode::emit_stderr(
                    "   🔄 Attempt 2: Grayscale ICC fix (-strip, 16-bit)",
                );
                match run_imagemagick_cjxl_pipeline_with_effort(ImagemagickCjxlPipelineRequest {
                    metadata_policy: JxlMetadataPolicy::Strip,
                    ..base_request
                }) {
                    Ok(()) => {
                        crate::progress_mode::emit_stderr(&format!(
                            "   {} Attempt 2 succeeded",
                            style("✅").green()
                        ));
                        crate::progress_mode::fallback_success();
                        return Ok(());
                    }
                    Err((m, c, stderr2)) => {
                        crate::progress_mode::emit_stderr(&format!(
                            "   {} Attempt 2 failed (magick: {}, cjxl: {})",
                            style("❌").red(),
                            if m {
                                style("✓").green()
                            } else {
                                style("✗").red()
                            },
                            if c {
                                style("✓").green()
                            } else {
                                style("✗").red()
                            }
                        ));

                        // Check if it's still a decode/pixel error and try 8-bit for 8-bit sources
                        if m && !c && is_decode_or_pixel_cjxl_error(&stderr2) {
                            let bit_depth = get_png_bit_depth(input).unwrap_or(16);
                            if bit_depth <= 8 {
                                // Attempt 3: -depth 8 -strip for 8-bit sources (no quality loss)
                                crate::progress_mode::emit_stderr(
                                    "   🔄 Attempt 3: 8-bit depth (-depth 8 -strip, 8-bit source confirmed)",
                                );
                                match run_imagemagick_cjxl_pipeline_with_effort(
                                    ImagemagickCjxlPipelineRequest {
                                        metadata_policy: JxlMetadataPolicy::Strip,
                                        output_depth: 8,
                                        ..base_request
                                    },
                                ) {
                                    Ok(()) => {
                                        crate::progress_mode::emit_stderr(&format!(
                                            "   {} Attempt 3 succeeded",
                                            style("✅").green()
                                        ));
                                        crate::progress_mode::fallback_success();
                                        return Ok(());
                                    }
                                    Err(_) => {
                                        crate::progress_mode::emit_stderr(&format!(
                                            "   {} Attempt 3 failed",
                                            style("❌").red()
                                        ));
                                    }
                                }
                            } else {
                                // Attempt 3: normalize ICC to sRGB, preserve 16-bit depth
                                crate::progress_mode::emit_stderr(
                                    "   🔄 Attempt 3: ICC normalization (sRGB, 16-bit source)",
                                );
                                if run_imagemagick_cjxl_pipeline_with_effort(
                                    ImagemagickCjxlPipelineRequest {
                                        icc_policy: JxlIccPolicy::NormalizeToSrgb,
                                        ..base_request
                                    },
                                ) == Ok(())
                                {
                                    crate::progress_mode::emit_stderr(&format!(
                                        "   {} Attempt 3 succeeded",
                                        style("✅").green()
                                    ));
                                    crate::progress_mode::fallback_success();
                                    return Ok(());
                                }
                                crate::progress_mode::emit_stderr(&format!(
                                    "   {} Attempt 3 failed",
                                    style("❌").red()
                                ));
                                crate::progress_mode::emit_stderr(
                                    "   ⚠️  16-bit source: refusing to downgrade to 8-bit",
                                );
                            }
                        }
                    }
                }
            } else if magick_ok && !cjxl_ok && is_decode_or_pixel_cjxl_error(&stderr) {
                let bit_depth = get_png_bit_depth(input).unwrap_or(16);
                if bit_depth <= 8 {
                    // Attempt 2: -strip -depth 8 for 8-bit sources (no quality loss)
                    crate::progress_mode::emit_stderr(
                        "   🔄 Attempt 2: 8-bit depth (-depth 8 -strip, 8-bit source confirmed)",
                    );
                    match run_imagemagick_cjxl_pipeline_with_effort(
                        ImagemagickCjxlPipelineRequest {
                            metadata_policy: JxlMetadataPolicy::Strip,
                            output_depth: 8,
                            ..base_request
                        },
                    ) {
                        Ok(()) => {
                            crate::progress_mode::emit_stderr(&format!(
                                "   {} Attempt 2 succeeded",
                                style("✅").green()
                            ));
                            crate::progress_mode::fallback_success();
                            return Ok(());
                        }
                        Err(_) => {
                            crate::progress_mode::emit_stderr(&format!(
                                "   {} Attempt 2 failed",
                                style("❌").red()
                            ));
                        }
                    }
                } else {
                    // Attempt 2: normalize ICC to sRGB, preserve 16-bit depth
                    crate::progress_mode::emit_stderr(
                        "   🔄 Attempt 2: ICC normalization (sRGB, 16-bit source)",
                    );
                    if run_imagemagick_cjxl_pipeline_with_effort(ImagemagickCjxlPipelineRequest {
                        icc_policy: JxlIccPolicy::NormalizeToSrgb,
                        ..base_request
                    }) == Ok(())
                    {
                        crate::progress_mode::emit_stderr(&format!(
                            "   {} Attempt 2 succeeded",
                            style("✅").green()
                        ));
                        crate::progress_mode::fallback_success();
                        return Ok(());
                    }
                    crate::progress_mode::emit_stderr(&format!(
                        "   {} Attempt 2 failed",
                        style("❌").red()
                    ));
                    crate::progress_mode::emit_stderr(
                        "   ⚠️  16-bit source: refusing to downgrade to 8-bit",
                    );
                }
            }

            // Final fallback: if nothing worked and we haven't tried -strip yet, try it as last resort
            if magick_ok && !cjxl_ok && !stderr.contains("-strip") {
                crate::progress_mode::emit_stderr("   🔄 Attempt (final): Last resort -strip");
                match run_imagemagick_cjxl_pipeline_with_effort(ImagemagickCjxlPipelineRequest {
                    metadata_policy: JxlMetadataPolicy::Strip,
                    ..base_request
                }) {
                    Ok(()) => {
                        crate::progress_mode::emit_stderr(&format!(
                            "   {} Final attempt succeeded",
                            style("✅").green()
                        ));
                        crate::progress_mode::fallback_success();
                        return Ok(());
                    }
                    Err(_) => {
                        crate::progress_mode::emit_stderr(&format!(
                            "   {} Final attempt failed",
                            style("❌").red()
                        ));
                    }
                }
            }

            // Signal-kill retry: cjxl crashed (OOM/SIGSEGV) — retry once at the configured
            // effort.
            if magick_ok && !cjxl_ok && is_cjxl_signal_killed(&stderr) {
                crate::progress_mode::emit_stderr(&format!(
                    "   {} Attempt (signal-kill retry): cjxl crash detected, retrying at effort {}",
                    style("🔄").yellow(),
                    effort
                ));
                match run_imagemagick_cjxl_pipeline_with_effort(ImagemagickCjxlPipelineRequest {
                    metadata_policy: JxlMetadataPolicy::Strip,
                    ..base_request
                }) {
                    Ok(()) => {
                        crate::progress_mode::emit_stderr(&format!(
                            "   {} Signal-kill retry succeeded (effort {})",
                            style("✅").green(),
                            effort
                        ));
                        crate::progress_mode::fallback_success();
                        return Ok(());
                    }
                    Err(_) => {
                        crate::progress_mode::emit_stderr(&format!(
                            "   {} Signal-kill retry failed",
                            style("❌").red()
                        ));
                    }
                }
            }
        }
    }

    crate::progress_mode::emit_stderr(&format!(
        "   {} All ImageMagick fallback attempts exhausted",
        style("❌").red()
    ));
    crate::log_upstream_error!(
        "Image conversion",
        "Failed {}: All ImageMagick+cjxl pipeline attempts failed. Possible causes: corrupted image data, unsupported format variant, or cjxl crash/OOM",
        input.display()
    );
    Err(std::io::Error::other(
        "ImageMagick fallback pipeline failed",
    ))
}

/// Fallback to `ImageMagick` for conversion if native tools fail, using the mode-locked JXL
/// policy.
///
/// # Errors
/// Returns an I/O error if conversion fails.
pub fn try_imagemagick_fallback(
    input: &Path,
    output: &Path,
    distance: f32,
    max_threads: usize,
    apple_compat: bool,
    ultimate: bool,
) -> std::result::Result<(), std::io::Error> {
    try_imagemagick_fallback_with_effort(
        input,
        output,
        crate::constants::jxl_distance_for_mode(distance, ultimate),
        crate::constants::jxl_effort_for_mode(ultimate),
        max_threads,
        apple_compat,
    )
}

/// Losslessly strip trailing data after JPEG EOI (0xFF 0xD9) so cjxl can use bitstream reconstruction.
///
/// Returns (`temp_path`, guard) if tail was stripped, or None if no tail or strip failed.
/// Strip JPEG extra data (trailing bytes) to a temporary file.
///
/// # Errors
/// Returns an I/O error if the file cannot be processed.
pub fn strip_jpeg_tail_to_temp(
    path: &Path,
) -> std::io::Result<Option<(std::path::PathBuf, tempfile::NamedTempFile)>> {
    let data = std::fs::read(path)?;
    if data.len() < 4 {
        return Ok(None);
    }

    // Must start with SOI
    if data.get(0..2) != Some(&[0xFF, 0xD8]) {
        return Ok(None);
    }

    let last_eoi = data
        .windows(2)
        .enumerate()
        .filter(|(_, w)| w == b"\xFF\xD9")
        .map(|(i, _)| i + 2) // i is FF, i+1 is D9, i+2 is the end of the marker (inclusive-slice-friendly index)
        .next_back();

    let end = match last_eoi {
        Some(e) if e < data.len() => e,
        _ => return Ok(None),
    };

    if end == data.len() {
        return Ok(None);
    }

    let temp = tempfile::Builder::new().suffix(".jpg").tempfile()?;
    std::fs::write(temp.path(), data.get(..end).unwrap_or(&[]))?;
    let temp_path = temp.path().to_path_buf();
    Ok(Some((temp_path, temp)))
}
