[package]
name = "img-av1"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "High-performance image quality analyzer - AV1/AVIF format converter"

[dependencies]
clap = { workspace = true }
image = { workspace = true }
serde = { workspace = true }
rayon = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
shared_utils = { workspace = true }
vid-av1 = { path = "../vid_av1" }
tempfile = { workspace = true }
console = { workspace = true }

[features]
default = ["v1_21"]
v1_21 = ["shared_utils/v1_21"]

[lints]
workspace = true
