#!/usr/bin/env python3
"""After four-lane training: aggregate ingest evidence and run verify-stack-readiness.

Does NOT run cargo test / check_all (CI). Fills runtime closure artifacts only.
"""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
ROOT = SCRIPT_DIR.parent.parent.parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from mfb_log_paths import (
    TRAINING_LOG_LANES,
    coerce_log_dir,
    persistent_log_dir,
)

LANES = tuple(TRAINING_LOG_LANES)


def _parse_finished(log_text: str) -> tuple[int, int, int] | None:
    m = re.search(
        r"Finished:\s*(\d+)\s+OK,\s*(\d+)\s+FAIL(?:\s+\((\d+)\s+label/score conflict\))?",
        log_text,
    )
    if not m:
        return None
    ok, fail = int(m.group(1)), int(m.group(2))
    lc = int(m.group(3) or 0)
    return ok, fail, lc


def aggregate_stamp(log_root: Path, stamp: str) -> dict[str, dict[str, int]]:
    out: dict[str, dict[str, int]] = {}
    for lane in LANES:
        log_path = log_root / lane / f"run_training_{stamp}.log"
        if not log_path.is_file():
            out[lane] = {"ok": 0, "fail": 0, "label_conflict": 0, "missing": 1}
            continue
        text = log_path.read_text(encoding="utf-8", errors="replace")
        parsed = _parse_finished(text)
        if parsed is None:
            out[lane] = {
                "ok": 0,
                "fail": 0,
                "label_conflict": 0,
                "missing": 0,
                "pending": 1,
            }
        else:
            ok, fail, lc = parsed
            out[lane] = {
                "ok": ok,
                "fail": fail,
                "label_conflict": lc,
                "missing": 0,
                "pending": 0,
            }
    return out


def write_runtime_evidence(
    repo_root: Path, stamp: str, summary: dict[str, dict[str, int]]
) -> Path:
    date = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    total_ok = sum(v.get("ok", 0) for v in summary.values())
    total_fail = sum(v.get("fail", 0) for v in summary.values())
    pending = any(v.get("pending") for v in summary.values())

    baseline = repo_root / "RUNTIME_BASELINE.md"
    lines = [
        f"# RUNTIME_EVIDENCE — stamp {stamp}",
        "",
        f"**Date:** {date}",
        "**Generated by:** post_training_closure.py",
        "",
        "| Lane | OK | FAIL | label_conflict | pending |",
        "|------|-----|------|----------------|---------|",
    ]
    for lane in LANES:
        s = summary[lane]
        lines.append(
            f"| {lane} | {s.get('ok', 0)} | {s.get('fail', 0)} | "
            f"{s.get('label_conflict', 0)} | {'yes' if s.get('pending') else 'no'} |"
        )
    lines.extend(
        [
            "",
            f"| **Total OK** | **{total_ok}** | **Total FAIL** | **{total_fail}** | pending={pending} |",
            "",
            f"**Log root:** `~/.modern_format_boost/logs/*/run_training_{stamp}.log`",
            "",
        ]
    )
    evidence = repo_root / f"RUNTIME_EVIDENCE_{stamp}.md"
    evidence.write_text("\n".join(lines) + "\n", encoding="utf-8")

    if not pending and total_ok > 0:
        append = (
            f"\n## Auto-append {date} stamp {stamp}\n\n"
            f"- Four-lane ingest aggregate: **{total_ok} OK**, **{total_fail} FAIL**\n"
            f"- Detail: [`RUNTIME_EVIDENCE_{stamp}.md`](RUNTIME_EVIDENCE_{stamp}.md)\n"
        )
        if baseline.is_file():
            baseline.write_text(
                baseline.read_text(encoding="utf-8") + append, encoding="utf-8"
            )
    return evidence


def run_verify_stack(conn_str: str, repo_root: Path, stamp: str) -> int:
    py = ROOT / ".venv" / "bin" / "python"
    if not py.is_file():
        py = Path(sys.executable)
    cmd = [
        str(py),
        str(SCRIPT_DIR / "training_pipeline.py"),
        "verify-stack-readiness",
        "--connstr",
        conn_str,
    ]
    log_root = coerce_log_dir(persistent_log_dir())
    log_path = log_root / f"runtime_v1_verify_stack_{stamp}.log"
    log_root.mkdir(parents=True, exist_ok=True)
    with log_path.open("w", encoding="utf-8") as log_f:
        proc = subprocess.run(
            cmd, cwd=str(ROOT), stdout=log_f, stderr=subprocess.STDOUT
        )
    status = "PASS" if proc.returncode == 0 else "FAIL"
    verify = repo_root / "RUNTIME_VERIFY.md"
    block = (
        f"\n## Auto-run {datetime.now(timezone.utc).strftime('%Y-%m-%d')} stamp {stamp}\n\n"
        f"| verify-stack-readiness | {status} |\n"
        f"| Exit code | {proc.returncode} |\n"
        f"| Log | {log_path} |\n"
    )
    if verify.is_file():
        verify.write_text(verify.read_text(encoding="utf-8") + block, encoding="utf-8")
    return proc.returncode


def finalize_image_quality_model(conn_str: str, repo_root: Path, stamp: str) -> int:
    py = ROOT / ".venv" / "bin" / "python"
    if not py.is_file():
        py = Path(sys.executable)
    cmd = [
        str(py),
        str(SCRIPT_DIR / "training_pipeline.py"),
        "finalize-image-quality-model",
        "--connstr",
        conn_str,
    ]
    log_root = coerce_log_dir(persistent_log_dir())
    log_path = log_root / f"runtime_v1_finalize_image_quality_{stamp}.log"
    log_root.mkdir(parents=True, exist_ok=True)
    with log_path.open("w", encoding="utf-8") as log_f:
        proc = subprocess.run(
            cmd, cwd=str(ROOT), stdout=log_f, stderr=subprocess.STDOUT
        )
    block = (
        f"\n## Auto-run {datetime.now(timezone.utc).strftime('%Y-%m-%d')} stamp {stamp}\n\n"
        f"| finalize-image-quality-model | {'PASS' if proc.returncode == 0 else 'FAIL'} |\n"
        f"| Exit code | {proc.returncode} |\n"
        f"| Log | {log_path} |\n"
    )
    finalize = repo_root / "RUNTIME_FINALIZE.md"
    if finalize.is_file():
        finalize.write_text(
            finalize.read_text(encoding="utf-8") + block, encoding="utf-8"
        )
    else:
        finalize.write_text(block, encoding="utf-8")
    return proc.returncode


def write_closure_cycle2(
    repo_root: Path, stamp: str, verify_code: int | None, pending: bool
) -> None:
    path = repo_root / "CLOSURE_CYCLE2.md"
    if pending:
        verify_status = "PENDING (lanes running)"
    elif verify_code is None:
        verify_status = "SKIPPED (--skip-verify)"
    elif verify_code == 0:
        verify_status = "PASS (exit 0)"
    else:
        verify_status = f"FAIL (exit {verify_code})"
    blocked = pending or (verify_code is not None and verify_code != 0)
    status = "BLOCKED" if blocked else "PASS"
    path.write_text(
        "\n".join(
            [
                f"# CLOSURE — Cycle 2 (Runtime) — stamp {stamp}",
                "",
                f"**Date:** {datetime.now(timezone.utc).strftime('%Y-%m-%d')}",
                "**Contract:** [`CLOSURE_CONTRACT_CYCLE2.md`](CLOSURE_CONTRACT_CYCLE2.md)",
                "",
                "| Gate | Status |",
                "|------|--------|",
                f"| Four-lane ingest evidence | {'PENDING' if pending else 'RECORDED'} |",
                f"| verify-stack-readiness | {verify_status} |",
                "",
                f"**Verdict:** {status}",
                "",
                "CI quality remains outside this closure (see [`PROJECT_SIGNOFF.md`](PROJECT_SIGNOFF.md)).",
                "",
            ]
        )
        + "\n",
        encoding="utf-8",
    )


def all_lanes_finished(log_root: Path, stamp: str) -> bool:
    for lane in LANES:
        log_path = log_root / lane / f"run_training_{stamp}.log"
        if not log_path.is_file():
            return False
        text = log_path.read_text(encoding="utf-8", errors="replace")
        if _parse_finished(text) is None:
            return False
    return True


def wait_for_lanes_finished(
    log_root: Path, stamp: str, *, poll_sec: float, timeout_sec: float | None
) -> bool:
    import time

    started = time.monotonic()
    while True:
        if all_lanes_finished(log_root, stamp):
            return True
        if timeout_sec is not None and (time.monotonic() - started) >= timeout_sec:
            return False
        print(
            f"  [WAIT] stamp={stamp} lanes still running; poll again in {poll_sec:.0f}s",
            flush=True,
        )
        time.sleep(poll_sec)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--stamp", required=True, help="Training session stamp, e.g. 20260605_215749"
    )
    parser.add_argument("--log-root", type=Path, default=None)
    parser.add_argument("--skip-verify", action="store_true")
    parser.add_argument(
        "--wait",
        action="store_true",
        help="Block until all four lanes log a Finished: line, then run closure.",
    )
    parser.add_argument(
        "--poll-sec",
        type=float,
        default=120.0,
        help="Poll interval when --wait (default 120s).",
    )
    parser.add_argument(
        "--timeout-sec",
        type=float,
        default=None,
        help="Optional max wait seconds; exit 1 if ingest not finished in time.",
    )
    args = parser.parse_args()

    log_root = (args.log_root or persistent_log_dir()).expanduser()
    if args.wait and not all_lanes_finished(log_root, args.stamp):
        if not wait_for_lanes_finished(
            log_root, args.stamp, poll_sec=args.poll_sec, timeout_sec=args.timeout_sec
        ):
            print(
                f"  [TIMEOUT] stamp={args.stamp} — not all lanes Finished:",
                file=sys.stderr,
            )
            raise SystemExit(1)
        print(f"  [WAIT] stamp={args.stamp} all lanes Finished — running closure")
    conn_str = (
        os.environ.get("MFB_PG_CONNSTR") or "postgresql://localhost/modern_format_boost"
    ).strip()

    summary = aggregate_stamp(log_root, args.stamp)
    pending = any(v.get("pending") for v in summary.values())
    evidence = write_runtime_evidence(ROOT, args.stamp, summary)
    print(f"  [OK] wrote {evidence}")

    finalize_code: int | None = None
    verify_code: int | None = None
    if not args.skip_verify and not pending:
        total_ok = sum(v.get("ok", 0) for v in summary.values())
        if total_ok > 0:
            finalize_code = finalize_image_quality_model(conn_str, ROOT, args.stamp)
            print(f"  [FINALIZE] finalize-image-quality-model exit={finalize_code}")
            verify_code = run_verify_stack(conn_str, ROOT, args.stamp)
            print(f"  [VERIFY] verify-stack-readiness exit={verify_code}")
        else:
            print("  [SKIP] verify-stack-readiness — zero OK ingests")
            verify_code = 1
    elif pending:
        print("  [SKIP] verify — one or more lanes still running (no Finished line)")
    elif args.skip_verify:
        print("  [SKIP] verify — --skip-verify")

    write_closure_cycle2(ROOT, args.stamp, verify_code, pending)
    blocked = (
        pending
        or (finalize_code is not None and finalize_code != 0)
        or (verify_code is not None and verify_code != 0)
    )
    print(
        f"  [OK] wrote CLOSURE_CYCLE2.md verdict={'PASS' if not blocked else 'BLOCKED'}"
    )
    raise SystemExit(0 if not blocked else 1)


if __name__ == "__main__":
    main()
