[package]
name = "vid"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
description = "High-performance video and animated media converter"

[dependencies]
rug = { workspace = true, optional = true }
gmp-mpfr-sys = { workspace = true, optional = true }

clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
rayon = { workspace = true }
anyhow = { workspace = true }
foundation = { path = "../foundation", default-features = false }
tempfile = { workspace = true }
tracing = { workspace = true }
which = { workspace = true }

[features]
default = ["foundation/default", "high-precision"]
high-precision = ["dep:rug", "dep:gmp-mpfr-sys", "foundation/high-precision"]
system-gmp = [
  "dep:gmp-mpfr-sys",
  "gmp-mpfr-sys/use-system-libs",
  "foundation/system-gmp",
]

[lints]
workspace = true
